Enable codeowners
enarx/crt0stack pull request #3
Opened 2020-11-11 20:18 UTC by mbestavros

2020-11-11 20:33 UTC, lkatalin submitted a review, later dismissed

2020-11-12 13:39 UTC, haraldh requested changes

2020-11-12 13:39 UTC, haraldh commented on .github/CODEOWNERS
> +*       @npmccallum
```suggestion
*       @npmccallum @haraldh 
```

2020-11-12 21:12 UTC, npmccallum approved these changes

2020-11-12 21:33 UTC, lkatalin approved these changes

2020-11-13 07:40 UTC, haraldh approved these changes

2020-11-13 07:48 UTC, merged